### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by Diego-Thomaz** [rubyforgood/applied-conservation#124]
I forked the project and when i try to run bundle install, it seems that one of the dependencies is out of date or discontinued. Console shows: could not find concurrent ruby 1.0.0 in any of the sources

**Comment by jgaskins** [comment]
@Diego-Thomaz Sorry about that, I've just updated `concurrent-ruby`. Looks like the version we were using was pulled from Rubygems for security reasons:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/108205/53292923-ba336d80-3798-11e9-939d-647cf03ea8c2.png">

Let us know if this fixes the problem. :-)

**Comment by sobrinho** [comment]
@Diego-Thomaz do you mind opening a PR?

**Comment by jgaskins** [comment]
@sobrinho A PR may not be necessary. I updated `concurrent-ruby` in the Gemfile, so we _should_ be good. As soon as we get confirmation from @Diego-Thomaz we can close this issue. Thanks!

**Comment by Diego-Thomaz** [comment]
@jgaskins , @sobrinho Now is working fine! :) I think i'll take one of the issues to work this week. Problably #95 . This one can be closed!

**Comment by maebeale** [comment]
Thanks folks!
