### ISSUE TITLE
David can add a new target

### ISSUE THREAD

**Issue by eaierstuck** [rubyforgood/applied-conservation#13]
GIVEN Project named Chena Valley exists
WHEN David views the list of targets
THEN he sees a button with text 'Add Target'
AND WHEN he clicks the Add Target button
THEN he sees a form with Title 'New Target'
AND he sees a Name input 
AND a Type dropdown (see target module spec for dropdown options)
AND a description textarea
AND WHEN he clicks save button (bottom of form)
THEN he is redirected to the targets index
AND he sees the newly added target in the index

**Comment by nleake** [comment]
[Task List – Edit.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1abe23caaee90012370477/125516c66e82c728ace21e0d46dc958928c2afa09cfdffc144aeb0b12d4f33316546b3397f8fe62bab0021435a0d4fa9150e0c47affddd2ea0b63c708b080aee84645e27d42103eee9dc4be05ce36ade0d97bcae8b44cae93827ef8e894b3c190c1a81f94f78.pdf)
[Task List.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1abe23caaee90012370477/125516c66e82c728ace21e0d46dc958928c2afa09cfdfd0fe64de29b234324676b5ee17e72d4b62cb94128025b0b4baa41585f45a8f88a7eafb76f62964e49bc8f3900299f7744eeaa880dbd03b0218e4d8db3ba8e4ec7e13e27e799c2.pdf)
