### ISSUE TITLE
David can see suggestions for Target names

### ISSUE THREAD

**Issue by eaierstuck** [rubyforgood/applied-conservation#32]
GIVEN David is creating a new Target
WHEN he clicks on the Target Name
THEN he sees a list of Name suggestions in a dropdown
AND WHEN he starts typing in the input field
THEN the list of suggestions only shows suggestions containing the input value
AND WHEN he selects a suggestion
THEN that suggestion is populated in the input
AND WHEN he clicks save
THEN he sees the value in the input as the Target name

**Comment by jtwhittington** [comment]
Done in #33
