### ISSUE TITLE
David sees Target Health Attribute Ratings

### ISSUE THREAD

**Issue by eaierstuck** [rubyforgood/applied-conservation#52]
GIVEN There is a health_attribute with name 'Flow' belonging to target_type 'Fresh water'
AND David selects 'Fresh water' from the type drop-down on a new target form
WHEN David saves the form
THEN he is on the target show page
AND he sees a list of target_health_attribute_ratings with one item
AND the target_health_attribute_rating has name 'Flow'
AND the target_health_attribute_rating has no rating

**Note: rename grades to ratings
**Note: drop target_health_attributes table

**Comment by bmurphy1** [comment]
Partly completed from branch 52-target-health-attribute-ratings.
