### ISSUE TITLE
Greg can edit default_health_attributes

### ISSUE THREAD

**Issue by jgaskins** [rubyforgood/applied-conservation#89]
Admins need to be able to edit the default health attributes that targets can choose from

**Comment by jgaskins** [comment]
We don't, really. The basic idea is that a "health attribute" is something like how you might rate the flow of a river (stagnant, poor flow, good flow, etc). It might not be a bad idea to add something like this to the DB seeds, actually.

**Comment by efl7a** [comment]
How about some of these attributes?

```  DEFAULT_HEALTH_ATTRIBUTES = [
    'pH',
    'temperature',
    'salinity',
    'nutrients',
    'species diversity',
    'seagrass condition',
    'flow',
    'invasive species',
    'plant cover',
    'soil quality',
    'wind erosion',
    'soil erosion'
    'population growth',
    'Other',
  ].freeze```

**Comment by maebeale** [comment]
completed
