### ISSUE TITLE
Add users to seeds

### ISSUE THREAD

**Issue by jgaskins** [rubyforgood/applied-conservation#92]
Add two users to seeds.rb:

Greg — `admin: true`
David — `admin: false`

**Comment by GabLeRoux** [comment]
You need a better description 🍻

**Comment by jgaskins** [comment]
@GabLeRoux Hello Gabriel! Thanks for your interest! Do you have any suggestions on how we can improve it?

**Comment by jgaskins** [comment]
Closed by #101
